console:
  auto_execute_prompt: false
dao_intercept: false
defaults:
  file_tree_scope: project_root
  terminal_cwd: project_root
language: en
paths:
  project_root: .
server:
  debug: false
  host: 127.0.0.1
  port: 5858
version: 1
